# Generated by Django 4.2.8 on 2023-12-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpost_date_alter_author_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='blog_image',
        ),
    ]
