# Generated by Django 4.2.8 on 2023-12-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_image_blogpost_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_images', models.ImageField(upload_to='recent/')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(max_length=250)),
                ('hashtags', models.CharField(max_length=250)),
                ('tips', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('tag_image', models.ImageField(upload_to='tag_image/')),
            ],
        ),
    ]
