# Generated by Django 4.2.8 on 2023-12-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='recipient',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
