# Generated by Django 4.2.8 on 2023-12-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_blogpost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='url_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
