# Generated by Django 4.2.8 on 2023-12-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_blogpost_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='url',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='url_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
